// Tests for the news filter. Run with: npm test.

const test = require('node:test');
const assert = require('node:assert/strict');
const { filterNews, isAutoGenerated, looksNonEnglish, isAdvertorial } = require('./newsFilter');

// Real headlines from the live CoinStats feed on 2026-09-25.
const bitget = { title: 'Bitget Reports $352M Security Breach, Halts Withdrawals', source: 'Crypto Breaking News', link: 'https://www.cryptobreaking.com/bitget-reports-352m-security-breach/' };
const benzinga = { title: "Bitcoin, Ethereum, XRP, Dogecoin Gain Amid Treasury Yields Spike: Analyst Says Whales Are 'Buying the Dip'", source: 'Benzinga', link: 'https://www.benzinga.com/crypto/x' };
const aiPiece = { title: 'Aave (AAVE) News Today: Why AAVE Is Up – 25 September 2026', source: 'CoinStats AI Articles', link: 'https://coinstats.app/ai/a/latest-news-for-aave' };
const french = { title: 'Se former au Bitcoin : les 11 meilleurs livres sur le BTC', source: 'Cryptoast.fr', link: 'https://cryptoast.fr/top-meilleurs-livres-bitcoin-btc/' };
const worldcoin = { title: 'Worldcoin longs get wrecked – And the data says more pain ahead', source: 'AMBCrypto', link: 'https://ambcrypto.com/worldcoin-longs-get-wrecked/' };

test('drops CoinStats auto-generated pieces', () => {
  assert.equal(isAutoGenerated(aiPiece), true);
  assert.equal(isAutoGenerated({ ...aiPiece, source: null }), true);
  assert.equal(isAutoGenerated(bitget), false);
});

test('drops non-English items, keeps English ones', () => {
  assert.equal(looksNonEnglish(french), true);
  assert.equal(looksNonEnglish({ ...french, link: 'https://example.com/x' }), true); // title alone
  for (const a of [bitget, benzinga, worldcoin]) assert.equal(looksNonEnglish(a), false, a.title);
});

test('filterNews keeps order of what remains', () => {
  assert.deepEqual(filterNews([benzinga, aiPiece, french, worldcoin, bitget]), [benzinga, worldcoin, bitget]);
});

// Turkish items that got through the first version, live on 2026-09-25.
test('drops Turkish headlines, keeps the same outlets\' English editions', () => {
  const tr = [
    { title: 'Eski Bitcoin balinası 4.500 BTC’yi yeni cüzdana taşıdı', source: 'Cointurk News TR', link: 'https://coin-turk.com/eski-bitcoin-balinasi' },
    { title: 'ABD’de İşlem Gören Spot Bitcoin Ve Ethereum ETF’lerinde Pozitif Seri Devam Ediyor! İşte Son Veriler', source: 'Bitcoin Sistemi Turkish', link: 'https://www.bitcoinsistemi.com/abdde' },
    { title: 'Analistler XRP için 2,30 dolar hedefini izliyor', source: 'Cointurk News TR', link: 'https://coin-turk.com/analistler-xrp' },
  ];
  for (const a of tr) assert.equal(looksNonEnglish(a), true, a.title);
  const en = [
    { title: 'Bitcoin whale transfers 4,500 BTC worth $381 million after 4-year inactivity', source: 'Cointurk News EN', link: 'https://en.coin-turk.com/bitcoin-whale' },
    { title: 'Positive Trend Continues in Spot Bitcoin and Ethereum ETFs Traded in the US! Here’s the Latest Data', source: 'Bitcoin Sistemi', link: 'https://en.bitcoinsistemi.com/positive' },
    { title: 'TRON Surpasses $30 Trillion in Total Transaction Volume', source: 'BlockchainReporter', link: 'https://blockchainreporter.net/tron' },
  ];
  for (const a of en) assert.equal(looksNonEnglish(a), false, a.title);
});

test('drops paid press releases', () => {
  assert.equal(isAdvertorial({ link: 'https://advertorial.cryptonews.com/press-releases/whisper' }), true);
  assert.equal(isAdvertorial({ link: 'https://cryptonews.com/news/x' }), false);
});
