// Which CoinStats news items to hide. Tested in newsFilter.test.js.
//
// - CoinStats' own auto-generated "X News Today: Why X Is Up/Down" pieces
//   (source "CoinStats AI Articles", links under coinstats.app/ai/) fill
//   most of the feed and bury real reporting.
// - The feed mixes in non-English outlets (e.g. Cryptoast.fr, Cointurk
//   News TR). They're spotted by a country-code domain, a source name
//   marked as another language ("... TR", "... Turkish"), letters only
//   Turkish uses (ı, ş, ğ), or several common foreign function words or
//   accented words.
// - Paid press releases (hosts like advertorial.cryptonews.com).

const NON_ENGLISH_TLDS = ['fr', 'de', 'es', 'it', 'pt', 'br', 'nl', 'ru', 'jp', 'kr', 'cn', 'tr', 'pl', 'vn', 'id'];
const FOREIGN_WORDS = new Set([
  'le', 'la', 'les', 'des', 'du', 'sur', 'pour', 'avec', 'est', 'une', 'dans', 'meilleurs',
  'el', 'los', 'las', 'de', 'para', 'con', 'por', 'del', 'una', 'que', 'y', 'en', 'su', 'se', 'al', 'mientras', 'sobre', 'entre',
  'der', 'die', 'das', 'und', 'mit', 'auf', 'ist', 'für',
  'os', 'em', 'uma', 'não', 'il', 'di', 'della', 'che', 'per',
  've', 'için', 'bir', 'ile', 'bu', 'işte',
]);
const FOREIGN_SOURCE = /\b(tr|turkish|türkçe|español|deutsch|français)\b/i;
const TURKISH_LETTERS = /[ıİşŞğĞ]/;
const ACCENTED = /[áéíóúñãõâêôàèìòùç]/;

function hostOf(link) {
  try {
    return new URL(link).hostname.toLowerCase();
  } catch {
    return '';
  }
}

export function isAutoGenerated(article) {
  return /coinstats ai/i.test(article.source || '')
    || (/(^|\.)coinstats\.app$/.test(hostOf(article.link)) && /\/ai\//.test(article.link || ''));
}

export function looksNonEnglish(article) {
  const tld = hostOf(article.link).split('.').pop();
  if (NON_ENGLISH_TLDS.includes(tld)) return true;
  if (FOREIGN_SOURCE.test(article.source || '')) return true;
  if (TURKISH_LETTERS.test(article.title || '')) return true;
  // Two or more signals: a foreign function word, or a word with an
  // accented letter (a single "Pokémon" or "café" doesn't count).
  const words = (article.title || '').toLowerCase().split(/[^\p{L}]+/u);
  const hits = words.filter((w) => FOREIGN_WORDS.has(w) || ACCENTED.test(w)).length;
  return hits >= 2;
}

export function isAdvertorial(article) {
  return /^advertorial\./.test(hostOf(article.link));
}

export function filterNews(articles) {
  return articles.filter((a) => !isAutoGenerated(a) && !looksNonEnglish(a) && !isAdvertorial(a));
}
