// Tests for the news filter. Run with: npm test.

const test = require('node:test');
const assert = require('node:assert/strict');
const { filterNews, isAutoGenerated, looksNonEnglish } = require('./newsFilter');

// Real headlines from the live CoinStats feed on 2026-09-25.
const bitget = { title: 'Bitget Reports $352M Security Breach, Halts Withdrawals', source: 'Crypto Breaking News', link: 'https://www.cryptobreaking.com/bitget-reports-352m-security-breach/' };
const benzinga = { title: "Bitcoin, Ethereum, XRP, Dogecoin Gain Amid Treasury Yields Spike: Analyst Says Whales Are 'Buying the Dip'", source: 'Benzinga', link: 'https://www.benzinga.com/crypto/x' };
const aiPiece = { title: 'Aave (AAVE) News Today: Why AAVE Is Up – 25 September 2026', source: 'CoinStats AI Articles', link: 'https://coinstats.app/ai/a/latest-news-for-aave' };
const french = { title: 'Se former au Bitcoin : les 11 meilleurs livres sur le BTC', source: 'Cryptoast.fr', link: 'https://cryptoast.fr/top-meilleurs-livres-bitcoin-btc/' };
const worldcoin = { title: 'Worldcoin longs get wrecked – And the data says more pain ahead', source: 'AMBCrypto', link: 'https://ambcrypto.com/worldcoin-longs-get-wrecked/' };

test('drops CoinStats auto-generated pieces', () => {
  assert.equal(isAutoGenerated(aiPiece), true);
  assert.equal(isAutoGenerated({ ...aiPiece, source: null }), true);
  assert.equal(isAutoGenerated(bitget), false);
});

test('drops non-English items, keeps English ones', () => {
  assert.equal(looksNonEnglish(french), true);
  assert.equal(looksNonEnglish({ ...french, link: 'https://example.com/x' }), true); // title alone
  for (const a of [bitget, benzinga, worldcoin]) assert.equal(looksNonEnglish(a), false, a.title);
});

test('filterNews keeps order of what remains', () => {
  assert.deepEqual(filterNews([benzinga, aiPiece, french, worldcoin, bitget]), [benzinga, worldcoin, bitget]);
});
