// Which CoinStats news items to hide. Tested in newsFilter.test.js.
//
// - CoinStats' own auto-generated "X News Today: Why X Is Up/Down" pieces
//   (source "CoinStats AI Articles", links under coinstats.app/ai/) fill
//   most of the feed and bury real reporting.
// - The feed mixes in non-English outlets (e.g. Cryptoast.fr). They're
//   spotted by a country-code domain or by several common French/Spanish/
//   German/Portuguese/Italian function words in the title.

const NON_ENGLISH_TLDS = ['fr', 'de', 'es', 'it', 'pt', 'br', 'nl', 'ru', 'jp', 'kr', 'cn', 'tr', 'pl', 'vn', 'id'];
const FOREIGN_WORDS = new Set([
  'le', 'la', 'les', 'des', 'du', 'sur', 'pour', 'avec', 'est', 'une', 'dans', 'meilleurs',
  'el', 'los', 'las', 'para', 'con', 'por', 'del', 'una', 'que',
  'der', 'die', 'das', 'und', 'mit', 'auf', 'ist', 'für',
  'os', 'em', 'uma', 'não', 'il', 'di', 'della', 'che', 'per',
]);

function hostOf(link) {
  try {
    return new URL(link).hostname.toLowerCase();
  } catch {
    return '';
  }
}

export function isAutoGenerated(article) {
  return /coinstats ai/i.test(article.source || '')
    || (/(^|\.)coinstats\.app$/.test(hostOf(article.link)) && /\/ai\//.test(article.link || ''));
}

export function looksNonEnglish(article) {
  const tld = hostOf(article.link).split('.').pop();
  if (NON_ENGLISH_TLDS.includes(tld)) return true;
  const words = (article.title || '').toLowerCase().split(/[^\p{L}]+/u);
  return words.filter((w) => FOREIGN_WORDS.has(w)).length >= 2;
}

export function filterNews(articles) {
  return articles.filter((a) => !isAutoGenerated(a) && !looksNonEnglish(a));
}
